Repository venth/aws-adfs, pull requests merged in 2022-10, with the labels that each got.

#346 Add support for Duo Verified Push MFA
  aws_adfs/_duo_universal_prompt_authenticator.py
  pyproject.toml
Labels: enhancement, python, hacktoberfest-accepted

#343 feature: Allow enforcement role_arn config variable
  aws_adfs/login.py
  aws_adfs/prepare.py
  aws_adfs/role_chooser.py
  test/test_config_preparation.py
  test/test_role_chooser.py
Labels: enhancement, python, hacktoberfest-accepted

#353 Add Duo Passcode support for both traditional and universal prompt
  aws_adfs/_duo_authenticator.py
  aws_adfs/_duo_universal_prompt_authenticator.py
  aws_adfs/authenticator.py
  aws_adfs/consts.py
  aws_adfs/login.py
  aws_adfs/prepare.py
Labels: enhancement, python, hacktoberfest-accepted

#356 Update duo auth method prompt to explicitly show Passcode as an option
  aws_adfs/_duo_universal_prompt_authenticator.py
Labels: python, hacktoberfest-accepted

#358 Automatically update help messages in README, and run pre-commit hooks in CI
  .github/workflows/build.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  aws_adfs/_azure_mfa_authenticator.py
  aws_adfs/commands.py
  aws_adfs/html_roles_fetcher.py
  aws_adfs/login.py
  poetry.lock
  pyproject.toml
  scripts/update-readme-help.sh
  test/test_account_aliases_fetcher.py
Labels: enhancement, dependencies, python, hacktoberfest-accepted

#360 Move release instructions to a script
  README.md
  scripts/release.sh
  scripts/update-readme-help.sh
Labels: hacktoberfest-accepted
